"""Deterministic generator for the cross-repo co-signed-receipt parity fixture.

Run as a module to (re)produce ``tests/fixtures/concordia_cosigned_receipt.json``:

    python -m tests.generate_cosign_fixture

The keys are derived from FIXED 32-byte seeds (publisher = 0x01*32, counterparty
= 0x02*32) and the receipt carries no timestamps, so the output is byte-stable
and regenerable. ``tests/test_cosign_producer.py`` asserts the committed fixture
matches what this generator produces and that it passes an independent port of
Verascore's ``verifyCounterpartyCosignatureStructural``.
"""

from __future__ import annotations

import base64
import json
import pathlib

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from concordia import cosign
from concordia.signing import KeyPair

PUBLISHER_SEED = bytes([1]) * 32
COUNTERPARTY_SEED = bytes([2]) * 32

FIXTURE_PATH = (
    pathlib.Path(__file__).parent / "fixtures" / "concordia_cosigned_receipt.json"
)


def keypair_from_seed(seed: bytes) -> KeyPair:
    sk = Ed25519PrivateKey.from_private_bytes(seed)
    return KeyPair(private_key=sk, public_key=sk.public_key())


def build_fixture() -> dict:
    publisher = keypair_from_seed(PUBLISHER_SEED)
    counterparty = keypair_from_seed(COUNTERPARTY_SEED)
    publisher_did = cosign.did_key_for(publisher)
    counterparty_did = cosign.did_key_for(counterparty)

    session_data = {
        "session_id": "concordia:session:cosign-fixture-0001",
        "counterparty_did": counterparty_did,
        "outcome": "agreed",
        "rounds": 4,
        "duration_seconds": 312,
        "terms_count": 3,
        "concessions_made": 2,
        "fulfillment_status": "fulfilled",
        "negotiation_competence": 90,
    }

    receipt = cosign.build_cosigned_receipt(
        session_data,
        publisher_did,
        counterparty_signer=cosign.keypair_signer(counterparty),
    )

    cp_pub_b64 = (
        base64.urlsafe_b64encode(counterparty.public_key_bytes())
        .rstrip(b"=")
        .decode("ascii")
    )

    return {
        "_comment": (
            "Concordia-produced counterparty co-signed receipt. Generated by "
            "tests/generate_cosign_fixture from concordia.cosign with FIXED seed "
            "keys (publisher seed=0x01*32, counterparty seed=0x02*32) so it is "
            "deterministic and regenerable. Cross-repo parity anchor: "
            "Wiki/concepts/concordia-bilateral-attestation-anchor-2026-06-09.md and "
            "Verascore src/lib/concordia-cosignature.ts. Verascore consumes this "
            "for the reverse-direction (producer->consumer) parity test."
        ),
        "publisher_did": publisher_did,
        "counterparty_did": counterparty_did,
        "counterparty_public_key_b64url": cp_pub_b64,
        "expected_counterparty_verified": True,
        "receipt": receipt,
    }


ENVELOPE_FIXTURE_PATH = (
    pathlib.Path(__file__).parent / "fixtures" / "concordia_publish_envelope.json"
)


def build_envelope_fixture() -> dict:
    """Full /api/publish transport-envelope fixture (the body Concordia POSTs).

    Built by the SAME code path the client uses (``build_publish_body``), with
    the same fixed seed keys and session data as the receipt fixture, so it is
    deterministic and regenerable. Verascore consumes this to verify the whole
    transport envelope — publisher signature over JSON.stringify(data),
    publicKey→agentId derivation, receipt extraction, normalization, and the
    counterparty co-signature — with its REAL route-layer functions.
    """
    from concordia.verascore import build_publish_body

    publisher = keypair_from_seed(PUBLISHER_SEED)
    counterparty = keypair_from_seed(COUNTERPARTY_SEED)
    publisher_did = cosign.did_key_for(publisher)
    counterparty_did = cosign.did_key_for(counterparty)

    session_data = {
        "session_id": "concordia:session:cosign-fixture-0001",
        "counterparty_did": counterparty_did,
        "outcome": "agreed",
        "rounds": 4,
        "duration_seconds": 312,
        "terms_count": 3,
        "concessions_made": 2,
        "fulfillment_status": "fulfilled",
        "negotiation_competence": 90,
    }

    body = build_publish_body(
        session_data,
        publisher,
        publisher_did,
        counterparty_signer=cosign.keypair_signer(counterparty),
    )

    return {
        "_comment": (
            "Concordia-produced /api/publish transport envelope (the complete "
            "POST body). Generated by tests/generate_cosign_fixture from "
            "concordia.verascore.build_publish_body with the same FIXED seed "
            "keys as concordia_cosigned_receipt.json (publisher seed=0x01*32, "
            "counterparty seed=0x02*32), so it is deterministic and "
            "regenerable. Verascore's test suite consumes this with its real "
            "route-layer functions (signature check over JSON.stringify(data), "
            "deriveAgentId, normalizeConcordiaReceipt, "
            "verifyCounterpartyCosignatureStructural)."
        ),
        "publisher_did": publisher_did,
        "counterparty_did": counterparty_did,
        "expected_counterparty_verified": True,
        "expected_outcome": "agreed",
        "body": body,
    }


def main() -> None:
    fixture = build_fixture()
    FIXTURE_PATH.write_text(
        json.dumps(fixture, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"wrote {FIXTURE_PATH}")
    envelope_fixture = build_envelope_fixture()
    ENVELOPE_FIXTURE_PATH.write_text(
        json.dumps(envelope_fixture, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {ENVELOPE_FIXTURE_PATH}")


if __name__ == "__main__":
    main()
