"""v0.6 hard gate: emitted attestation schema carries the v0.6 URN.

The bundled JSON Schema files at ``schemas/`` are the canonical write
surface that the Python SDK loads via ``concordia.schema_validator``.
This test asserts the attestation schema carries the ``v0.6`` URN and that
attestations generated by ``generate_attestation()`` validate cleanly
against it.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from concordia import (
    Agent,
    BasicOffer,
    SessionState,
    generate_attestation,
    is_valid_attestation,
)


_SCHEMAS_DIR = Path(__file__).resolve().parent.parent / "schemas"


def _load_schema(name: str) -> dict:
    with open(_SCHEMAS_DIR / name) as f:
        return json.load(f)


class TestSchemaUrnsAtV06:
    """Emit-side attestation schema carries the 0.6.0 URN."""

    def test_attestation_schema_at_v06(self):
        schema = _load_schema("attestation.schema.json")
        assert schema["$id"] == "urn:concordia:schema:attestation:v0.6"

    def test_reference_schema_remains_v05_companion(self):
        schema = _load_schema("reference.schema.json")
        assert schema["$id"] == "urn:concordia:schema:reference:v0.5"

    def test_attestation_schema_embeds_v06_reference_def(self):
        schema = _load_schema("attestation.schema.json")
        ref_def = schema["$defs"]["reference"]
        assert "id" in ref_def["required"]
        assert "type" in ref_def["required"]
        assert "relationship" in ref_def["required"]
        assert "extensions" not in ref_def["properties"]


@pytest.fixture
def agreed_session():
    seller = Agent("seller_v05_emit")
    buyer = Agent("buyer_v05_emit")
    terms = {"price": {"value": 100.0, "currency": "USD"}, "qty": {"value": 1}}
    session = seller.open_session(counterparty=buyer.identity, terms=terms)
    buyer.join_session(session)
    buyer.accept_session()
    seller.send_offer(BasicOffer(terms={
        "price": {"value": 100.0, "currency": "USD"},
        "qty": {"value": 1},
    }))
    buyer.accept_offer()
    assert session.state == SessionState.AGREED
    return session, seller, buyer


def _key_pairs(seller, buyer):
    return {
        seller.identity.agent_id: seller.key_pair,
        buyer.identity.agent_id: buyer.key_pair,
    }


class TestGeneratedAttestationsConformToV06:
    """Attestations generated today validate against the v0.6 schema."""

    def test_minimal_attestation_validates(self, agreed_session):
        session, seller, buyer = agreed_session
        att = generate_attestation(session, _key_pairs(seller, buyer))
        assert is_valid_attestation(att)

    def test_attestation_with_v06_optional_reference_fields(self, agreed_session):
        session, seller, buyer = agreed_session
        refs = [
            {
                "type": "receipt",
                "id": "att_prior",
                "relationship": "extends",
                "version": "0.4.0",
                "signed_at": "2026-04-20T12:00:00Z",
                "signer_did": "did:web:example.org:agent-7",
            },
        ]
        att = generate_attestation(
            session, _key_pairs(seller, buyer), references=refs
        )
        assert is_valid_attestation(att)
        emitted = att["references"][0]
        assert emitted["version"] == "0.4.0"
        assert emitted["signed_at"] == "2026-04-20T12:00:00Z"
        assert emitted["signer_did"] == "did:web:example.org:agent-7"
