/**
 * Direct unit tests for the CPython-parity rendering internals:
 *
 * - `src/internal/py-repr.ts` (pyRepr / pyReprString / pyReprNumber): must
 *   byte-match CPython `repr()` for the JSON-shaped value space (enum
 *   `ValueError` text in the mandate engine + session layer, `required`
 *   messages in the jsonschema layer).
 * - `src/internal/py-json.ts` (pyJsonDumps): must byte-match CPython
 *   `json.dumps(value, sort_keys=True)` (constraint rendering in the
 *   schema-validation error format).
 *
 * PARITY SOURCE: every fixture expectation is CPython output, generated by
 * scripts/gen-pyrepr-fixtures.py (stdlib-only) and synced by
 * scripts/sync-fixtures-from-python.mjs into
 * tests/fixtures/internal/py_render_vectors.json. Hard-coded expectations in
 * the direct tests below were each computed with CPython 3.12 and carry the
 * Python expression they came from in a comment. Nothing here is JS output
 * copied back as its own expectation, except the explicitly marked
 * KNOWN PARITY RESIDUAL pins, which freeze documented divergences.
 *
 * INPUT DECODING: fixture inputs ride inside JSON, which cannot carry the
 * full value space under test, so the generator tags two shapes (see its
 * docstring) and `decodeInput` below reverses them:
 * - `{"$nonfinite": "nan" | "inf" | "-inf"}` -> NaN / Infinity / -Infinity
 * - `{"$float": n}` -> the number n, registered as float-sourced in the
 *   FloatConstraintMap (or rootIsFloat when at the root), mirroring how
 *   `validation/schemas.ts` marks float-sourced constraint locations.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

import { pyRepr, pyReprString, pyReprNumber } from '../src/internal/py-repr.js';
import { pyJsonDumps, type FloatConstraintMap } from '../src/internal/py-json.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Fixture loading + tagged-input decoding
// ---------------------------------------------------------------------------

interface ReprCase {
  name: string;
  input: unknown;
  expected: string;
}
interface JsonCase {
  name: string;
  input: unknown;
  expected: string;
}
interface Fixtures {
  python_version: string;
  repr_cases: ReprCase[];
  json_cases: JsonCase[];
}

const fixtures: Fixtures = JSON.parse(
  readFileSync(
    join(__dirname, 'fixtures/internal/py_render_vectors.json'),
    'utf8',
  ),
);

interface Decoded {
  value: unknown;
  /** True when this position was a Python FLOAT (tagged by the generator). */
  isFloat: boolean;
}

/**
 * Reverse the generator's input encoding. Objects get their float-sourced
 * keys registered in `floats` (the same WeakMap-of-object-node shape the
 * schema bundle hands pyJsonDumps); a `$float` at the root surfaces as
 * `isFloat` so the caller can pass `rootIsFloat`.
 */
function decodeInput(node: unknown, floats: FloatConstraintMap): Decoded {
  if (Array.isArray(node)) {
    return {
      value: node.map((el) => decodeInput(el, floats).value),
      isFloat: false,
    };
  }
  if (node !== null && typeof node === 'object') {
    const obj = node as Record<string, unknown>;
    if ('$nonfinite' in obj) {
      const v =
        obj.$nonfinite === 'nan'
          ? NaN
          : obj.$nonfinite === 'inf'
            ? Infinity
            : -Infinity;
      return { value: v, isFloat: true };
    }
    if ('$float' in obj) {
      return { value: obj.$float as number, isFloat: true };
    }
    const out: Record<string, unknown> = {};
    const floatKeys = new Set<string>();
    for (const [k, v] of Object.entries(obj)) {
      const d = decodeInput(v, floats);
      out[k] = d.value;
      if (d.isFloat) floatKeys.add(k);
    }
    if (floatKeys.size > 0) floats.set(out, floatKeys);
    return { value: out, isFloat: false };
  }
  return { value: node, isFloat: false };
}

// ---------------------------------------------------------------------------
// pyRepr: CPython repr() parity (fixture vectors)
// ---------------------------------------------------------------------------

describe('pyRepr CPython repr() parity (Python-generated vectors)', () => {
  for (const c of fixtures.repr_cases) {
    it(c.name, () => {
      const { value } = decodeInput(c.input, new WeakMap());
      expect(pyRepr(value)).toBe(c.expected);
    });
  }
});

// ---------------------------------------------------------------------------
// pyJsonDumps: CPython json.dumps(..., sort_keys=True) parity (fixture vectors)
// ---------------------------------------------------------------------------

describe('pyJsonDumps CPython json.dumps parity (Python-generated vectors)', () => {
  for (const c of fixtures.json_cases) {
    it(c.name, () => {
      const floats: FloatConstraintMap = new WeakMap();
      const { value, isFloat } = decodeInput(c.input, floats);
      expect(pyJsonDumps(value, floats, isFloat)).toBe(c.expected);
    });
  }
});

// ---------------------------------------------------------------------------
// pyReprString / pyReprNumber direct exports
// ---------------------------------------------------------------------------

describe('pyReprString export', () => {
  it('selects double quotes only when a single quote is present alone', () => {
    expect(pyReprString("it's")).toBe('"it\'s"'); // CPython: repr("it's")
    expect(pyReprString('say "hi"')).toBe("'say \"hi\"'"); // CPython: repr('say "hi"')
    expect(pyReprString('a\'b"c')).toBe("'a\\'b\"c'"); // CPython: repr('a\'b"c')
  });

  it('escapes by code point with fixed-width lowercase hex', () => {
    expect(pyReprString('\x9c')).toBe("'\\x9c'"); // CPython: repr('\x9c')
    expect(pyReprString('\u200b')).toBe("'\\u200b'"); // CPython: repr('\u200b')
    expect(pyReprString('\u{f0000}')).toBe("'\\U000f0000'"); // CPython: repr('\U000f0000')
  });
});

describe('pyReprNumber export', () => {
  it('renders non-finite floats as CPython repr literals', () => {
    expect(pyReprNumber(NaN)).toBe('nan'); // CPython: repr(float("nan"))
    expect(pyReprNumber(Infinity)).toBe('inf'); // CPython: repr(float("inf"))
    expect(pyReprNumber(-Infinity)).toBe('-inf'); // CPython: repr(float("-inf"))
  });

  it('renders negative zero as "0" (a JSON wire "-0" is Python int 0)', () => {
    expect(pyReprNumber(-0)).toBe('0'); // CPython: repr(json.loads("-0")) == repr(0)
  });
});

// ---------------------------------------------------------------------------
// JS-only value space (no Python counterpart on the wire; pinned for totality)
// ---------------------------------------------------------------------------

describe('pyRepr JS-only value space', () => {
  it('maps undefined to None (same rendering as null)', () => {
    expect(pyRepr(undefined)).toBe('None');
    expect(pyRepr(null)).toBe('None'); // CPython: repr(None)
  });

  it('renders bigint as the matching Python int repr', () => {
    expect(pyRepr(7n)).toBe('7'); // CPython: repr(7)
    expect(pyRepr(-12345678901234567890n)).toBe('-12345678901234567890');
  });

  it('stays total on non-wire JS types via String()', () => {
    // Symbols/functions cannot appear in a JSON-shaped wire value; the
    // helper falls back to String() rather than throwing.
    expect(pyRepr(Symbol('x'))).toBe('Symbol(x)');
  });
});

// ---------------------------------------------------------------------------
// pyJsonDumps non-serializable rejection (Python raises TypeError; so do we)
// ---------------------------------------------------------------------------

describe('pyJsonDumps non-JSON leaf rejection', () => {
  it('throws TypeError on undefined / bigint / function / symbol roots', () => {
    expect(() => pyJsonDumps(undefined)).toThrow(TypeError);
    expect(() => pyJsonDumps(7n)).toThrow(TypeError);
    expect(() => pyJsonDumps(() => 1)).toThrow(TypeError);
    expect(() => pyJsonDumps(Symbol('x'))).toThrow(TypeError);
  });

  it('throws TypeError on non-JSON leaves nested in containers', () => {
    expect(() => pyJsonDumps([1, undefined])).toThrow(TypeError);
    expect(() => pyJsonDumps({ a: 7n })).toThrow(TypeError);
  });
});

// ---------------------------------------------------------------------------
// FloatConstraintMap scoping semantics
// ---------------------------------------------------------------------------

describe('pyJsonDumps FloatConstraintMap scoping', () => {
  it('marks per object NODE, not per key name', () => {
    const a = { x: 1 };
    const b = { x: 1 };
    const floats: FloatConstraintMap = new WeakMap([[a, new Set(['x'])]]);
    // CPython: json.dumps({"a": {"x": 1.0}, "b": {"x": 1}}, sort_keys=True)
    expect(pyJsonDumps({ a, b }, floats)).toBe(
      '{"a": {"x": 1.0}, "b": {"x": 1}}',
    );
  });

  it('treats an unmarked integral root as an int by default', () => {
    expect(pyJsonDumps(2)).toBe('2'); // CPython: json.dumps(2)
  });
});

// ---------------------------------------------------------------------------
// KNOWN PARITY RESIDUAL pins (documented divergences; expectations are the
// CURRENT JS output, frozen so any drift is loud. Each comment records what
// CPython produces instead and why the divergence is out of reach.)
// ---------------------------------------------------------------------------

describe('KNOWN PARITY RESIDUAL pins', () => {
  it('float exponent switchover at 1e16 (json.dumps)', () => {
    // KNOWN PARITY RESIDUAL: CPython json.dumps(1e16) == "1e+16" (Python
    // switches float repr to exponent notation at 1e16; JS String() switches
    // at 1e21). Unreachable from the bundled schemas (documented in
    // py-json.ts); the Python-generated fixtures would catch such a value
    // the moment one appeared. Pinned at current JS output.
    expect(pyJsonDumps(1e16, undefined, true)).toBe('10000000000000000.0');
  });

  it('float exponent switchover at 1e-5 (json.dumps)', () => {
    // KNOWN PARITY RESIDUAL: CPython json.dumps(0.00001) == "1e-05" (Python
    // switches to exponent notation below 1e-4; JS below 1e-7). Same
    // unreachability argument as above. Pinned at current JS output.
    expect(pyJsonDumps(0.00001)).toBe('0.00001');
  });

  it('float exponent switchover at 1e-5 (repr)', () => {
    // KNOWN PARITY RESIDUAL: CPython repr(1e-05) == "1e-05". A JSON wire
    // 0.00001 reprs as "0.00001" here. Only affects enum-ValueError text for
    // a value that is rejected either way (TemporalMode / MessageType are
    // tiny ASCII string enums); no fail-open. Pinned at current JS output.
    expect(pyRepr(0.00001)).toBe('0.00001');
  });

  it('wire float 1e+16 collapses to int rendering (repr)', () => {
    // KNOWN PARITY RESIDUAL: a JSON wire "1e+16" is Python float 1e16
    // (repr "1e+16") but reaches JS as a plain integral number, which the
    // module renders as the Python INT repr by its documented value-space
    // collapse (JSON carries no int/float tag). CPython:
    // repr(10000000000000000) == "10000000000000000". Pinned.
    expect(pyRepr(1e16)).toBe('10000000000000000');
  });

  it('array elements cannot be float-marked (json.dumps)', () => {
    // KNOWN PARITY RESIDUAL: CPython json.dumps([1.0]) == "[1.0]", but the
    // FloatConstraintMap registry only keys OBJECT properties, so an
    // integral float inside an array renders as an int. No bundled schema
    // carries a float inside an array (documented in py-json.ts). Pinned.
    const floats: FloatConstraintMap = new WeakMap();
    expect(pyJsonDumps([1], floats)).toBe('[1]');
  });
});
