#!/usr/bin/env python3
"""Generate Ed25519 signing parity fixtures FROM the Concordia Python reference.

Run from the repo root (or anywhere with `concordia` importable). Emits a JSON
document to stdout. The JS test suite (tests/signing.test.ts) asserts that the
TypeScript signing layer produces byte-identical signatures and that it accepts
exactly these Python-produced signatures, rejecting the tampered variants.

This is the parity source of truth: signatures here come straight from
`concordia.signing.sign_message`, never hand-authored. Synced into the JS test
surface by scripts/sync-fixtures-from-python.mjs.
"""

from __future__ import annotations

import base64
import copy
import json
import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from concordia import signing


def _kp_from_seed(seed: bytes) -> signing.KeyPair:
    sk = Ed25519PrivateKey.from_private_bytes(seed)
    return signing.KeyPair(private_key=sk, public_key=sk.public_key())


# A fixed 32-byte seed so the fixtures are fully deterministic and reproducible
# across runs and machines (the raw private key IS the Ed25519 seed in both the
# Python `cryptography` lib and JS `@noble/curves`).
SEED = bytes(range(32))

# A second, distinct key used for the wrong-key rejection case.
OTHER_SEED = bytes(range(100, 132))

# Representative message payloads spanning the canonical-JSON edge cases the
# canonicalizer (PR 1) already covers: key ordering, nesting, arrays, unicode,
# numbers, null/bool, and the `signature` field that MUST be stripped before
# signing.
PAYLOADS = [
    {"a": 1},
    {"message_type": "OFFER", "amount": 42, "nested": {"z": 1, "a": 2}},
    {"items": [3, 1, 2], "tag": "deal"},
    {"greeting": "héllo", "emoji": "✓"},
    {"p": 1.5, "n": -3.25, "zero": 0},
    {"x": None, "t": True, "f": False},
    {
        "message_type": "ACCEPT",
        "signature": "THIS_FIELD_MUST_BE_STRIPPED_BEFORE_SIGNING",
        "session_id": "sess-123",
        "terms": {"price": 100, "qty": 5},
    },
    {"nested": {"deep": {"deeper": {"leaf": "value", "arr": [{"b": 2, "a": 1}]}}}},
]


def main() -> None:
    kp = _kp_from_seed(SEED)
    other_kp = _kp_from_seed(OTHER_SEED)

    cases = []
    for payload in PAYLOADS:
        sig = signing.sign_message(payload, kp)
        # Sanity: Python must verify its own signature.
        assert signing.verify_signature(payload, sig, kp.public_key), payload
        cases.append(
            {
                "payload": payload,
                "expected_signature": sig,
                "expected_canonical": signing.canonical_json(
                    {k: v for k, v in payload.items() if k != "signature"}
                ).decode("utf-8"),
            }
        )

    # Tamper cases: a valid (payload, signature) plus a description of the
    # mutation the verifier must reject. The JS suite applies each mutation and
    # asserts verify(...) === False.
    base_payload = {"message_type": "OFFER", "amount": 42, "currency": "USD"}
    base_sig = signing.sign_message(base_payload, kp)
    assert signing.verify_signature(base_payload, base_sig, kp.public_key)

    tampered_payload = dict(base_payload)
    tampered_payload["amount"] = 43
    assert not signing.verify_signature(
        tampered_payload, base_sig, kp.public_key
    )

    # A signature with a single flipped byte (still valid base64url) must fail.
    raw = bytearray(base64.urlsafe_b64decode(base_sig))
    raw[0] ^= 0x01
    flipped_sig = base64.urlsafe_b64encode(bytes(raw)).decode()
    assert not signing.verify_signature(
        base_payload, flipped_sig, kp.public_key
    )

    # The correct signature under the wrong public key must fail.
    assert not signing.verify_signature(
        base_payload, base_sig, other_kp.public_key
    )

    tamper = {
        "base_payload": base_payload,
        "valid_signature": base_sig,
        "tampered_payload": tampered_payload,
        "flipped_signature": flipped_sig,
        "wrong_public_key_b64": other_kp.public_key_b64(),
    }

    doc = {
        "_comment": (
            "Generated by js-sdk/scripts/gen-signing-fixtures.py from "
            "concordia.signing. Signatures are Python-produced; do not edit by hand."
        ),
        "algorithm": "EdDSA",
        "seed_hex": SEED.hex(),
        "public_key_b64": kp.public_key_b64(),
        "cases": cases,
        "tamper": tamper,
    }

    json.dump(doc, sys.stdout, ensure_ascii=False, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
