export {
  ATTESTATION_VERSION,
  DEFAULT_ATTESTATION_VALIDITY_SECONDS,
  MAX_ATTESTATION_VALIDITY_SECONDS,
  VALIDITY_TEMPORAL_MODES,
  VALUE_RANGE_BUCKETS,
  MAX_CATEGORY_LENGTH,
  MAX_REFERENCES,
  MAX_SET_BINDING_TRANSCRIPT_MESSAGES,
  AttestationError,
  generateAttestation,
  countersignAttestation,
  verifyAttestationCountersignature,
  verifyReceiptSetBinding,
  generateReceiptSummary,
  computeTranscriptHash,
  validateValidityTemporal,
  isValidNow,
  type ReceiptSetBindingResult,
  type ReceiptSetBindingState,
  type ValidityTemporal,
  type GenerateAttestationOptions,
} from './attestation.js';
